# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: ru-RU
title: Антон Вакуленко
description: Фронтенд разработчик
email: anton@avakulenko.ru
url: http://avakulenko.ru
theme: jekyll-theme-minimal

# Social Networks
github:
  username:  vzhikness
twitter:
  username: vzhikness
facebook:
  username: vzhikness
linkedin:
  username: antonvakulenko
telegram:
  username: vzhikness
social:
  name: Anton Vakulenko
  links:
    - https://twitter.com/vzhikness
    - https://www.facebook.com/vzhikness
    - https://www.linkedin.com/in/antonvakulenko
    - https://www.github.com/vzhikness
